### ISSUE TITLE
How to add SQL queries to the queue system ? 

### ISSUE THREAD

**Issue by zilveer** [tarantool-php/queue#16]
Hi,
I wonder if there is any example out there where I can use the php-client (for Tarantool ) to actually add SQL queries to the queue system in utube order or fifo order?

Thanks very much for any reply

Regards Zilveer

**Comment by rybakit** [comment]
Could you elaborate on what you need SQL queries for?

**Comment by zilveer** [comment]
@rybakit
I am using the php-client to save data in Tarantool in SQL mode since I am more familiar with that then NoSQL.

Regards

**Comment by rybakit** [comment]
Sorry, I still don't get what are you trying to archive and what "add SQL queries to the queue system" means.

**Comment by zilveer** [comment]
@rybakit I mean like this

https://github.com/tarantool-php/client/issues/52#issuecomment-515286765

**Comment by rybakit** [comment]
@zilveer Your sample code doesn't make sense to me.

**Comment by zilveer** [comment]
@rybakit ok let's make a new try (I hope I can clarify it better now).

Basically can you provide me an example where I can put a query(space or SQL query ) to the queue by using the php-client ?

**Comment by rybakit** [comment]
@zilveer Let's forget for a moment about PHP and focus on the data. Tarantool queue supports several queue types, as an example let's take `fifottl` which stores tasks in a space with the following [format](https://github.com/tarantool/queue/blob/master/queue/abstract/driver/fifottl.lua#L57-L66):

```lua
{
    {name = 'task_id', type = num_type()},
    {name = 'status', type = str_type()},
    {name = 'next_event', type = num_type()},
    {name = 'ttl', type = num_type()},
    {name = 'ttr', type = num_type()},
    {name = 'pri', type = num_type()},
    {name = 'created', type = num_type()},
    {name = 'data', type = '*'}
}
```

Could you provide a SQL query that you want to add (?) to this space?

**Comment by zilveer** [comment]
@rybakit perhaps Tarantool queue isn't doing what I expect it to do.
I would like to add queries to the queue, so once the worker picks up the job, the query gets executes. perhaps this isn't even possible with this package ?
Sorry but I don't get it

Regards

**Comment by rybakit** [comment]
This library is just a php binding for lua's [tarantool/queue](https://github.com/tarantool/queue), and IMHO it's clear enough from both README's what this library is capable of. Given that, to add a query to the queue you can simply call `$queue->put('<my-sql-query>')`, no more, no less. The rest of the logic, like picking up the right job, executing it, retrying it in case of failure, etc should be done by your worker and is out of the scope of this library. For the worker support, take a look at [Tarantool JobQueue](https://github.com/tarantool-php/jobqueue) and [Tarantool JobServer](https://github.com/tarantool-php/jobserver) (they don't yet support the recent tarantool/client, but at least you can get an idea of how tarantool/queue can be used). Even more, if all you need from your worker is to execute sql inside a tarantool server, you don't even need php for that, just use lua.

**Comment by zilveer** [comment]
@rybakit thank you for the explanation.

Regards
