### ISSUE TITLE
Add tarantool/client dependency new version 0.10

### ISSUE THREAD

**Issue by SonSergei** [tarantool-php/queue#19]
composer req -W tarantool/client:v0.10.0
./composer.json has been updated
Running composer update tarantool/client --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires tarantool/client v0.10.0, found tarantool/client[v0.10.0] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - tarantool/queue is locked to version v0.9.0 and an update of this package was not requested.

**Comment by rybakit** [comment]
Fixed via https://github.com/tarantool-php/queue/commit/1750bc13cd6a66206c63c8f42323efe4b30b0cc9.
